### ISSUE TITLE
showprogress option not working in IQ solver

### ISSUE THREAD

**Issue by p-ortega** [JuliaEarth/ImageQuilting.jl#52] opened 2023-05-22 03:00 UTC
Hi!

I'm running a simulation using the showprogress option in the IQ solver as:

```
nreal = 50

#conditional simulation with loaded boreholes
condsim = SimulationProblem(geodata, domain, :prop1, nreal)

solver = IQ(:prop1 => 
            (trainimg=TI, 
            tilesize=(40,40,5), 
            overlap = (1/4, 1/4, 1/4)),
            showprogress = true)
solution = solve(condsim, solver)

```
but no progress is being shown in the terminal. 

Thanks!!

**Comment by juliohm** [comment] 2023-05-22 12:18
Hi @p-ortega , where you are running the script? Pluto? Jupyter? Can you try in the Julia REPL?

**Comment by p-ortega** [comment] 2023-05-23 04:13
Hi @juliohm 

I've tried running it in Jupyter, in the prompt (windows) with `julia script-name.j`l and in the REPL with` julia> include("path/to/script-name.jl")` but no luck.

**Comment by juliohm** [comment] 2023-05-23 06:53
Can you please confirm the version of the package you are using?

Em ter., 23 de mai. de 2023 01:14, Pablo Ortega ***@***.***>
escreveu:

**Comment by p-ortega** [comment] 2023-05-23 07:34
v0.18.7 and Julia v1.8.5

**Comment by juliohm** [comment] 2023-05-23 08:22
Thank you @p-ortega , I can reproduce the issue. The problem is that our high-level IQ solver is calling the underlying iqsim function to generate each realization one-by-one in parallel, so the option showprogress doesn't take effect. We need to solve this issue probably in GeoStatsBase.jl by providing a general progress mechanism for all GeoStats.jl solvers.

In the meantime, if you need showprogress, I recommend using the more low-level iqsim function in this package.

**Comment by juliohm** [comment] 2023-05-30 00:34
Fixed in the latest release.

**Closed by juliohm** 2023-05-30 00:34 UTC
Labels: bug
